[package]
name = "MessagePack"
version = "0.1.0"
edition = "2021"

[dependencies]
rmp = "0.8.14"
rmp-serde = "1.3.0"
rmpv = "1.3.0"
serde = { version = "1.0.219", features = ["derive"] }
serde-reflection = "0.5.0"
serde_json = "1.0.140"
